format_version: 3
pipelines:
  deploy-to-kubernetes-staging:
    group: demo
    template: deploy_to_cluster
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/gocd-contrib/helm-deploy-script.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: helm-deploy-script
      upstream_functional:
        pipeline: functional-tests
        stage: defaultStage
        name: upstream_functional
      upstream_pref:
        pipeline: acceptance-tests
        stage: defaultStage
        name: upstream_pref
    parameters:
      namespace: staging
      upstream: ci-build-and-test/functional-tests
      release_name: staging
